webServerPort: 8080
rtmpServerPort: 1935
instanceDetails:
  name: Movie Night
  title: Movie Night Server
  logo: /img/logo.svgn
  summary: Movie Night
videoSettings:
  chunkLengthInSeconds: 4
  streamingKey: ${stream_key}
  streamQualities:
    - low:
      videoBitrate: 2660
      audioPassthrough: true
      encoderPreset: fast
s3:
  enabled: true
  endpoint: https://sfo3.digitaloceanspaces.com
  servingEndpoint: https://sfo3.digitaloceanspaces.com
  accessKey: ${do_spaces_token}
  secret: ${do_spaces_secret}
  region: sfo3
  bucket: sdsa-owncast-files